AllCops:
  Include:
    - !ruby/regexp /\.rb$/
  Exclude:
   - 'spec/*'
Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Semicolon:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 20
Metrics/AbcSize:
  Max: 30
