AllCops:
  Include:
    - !ruby/regexp /\.rb$/
Documentation:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/Semicolon:
  Enabled: false
Metrics/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 15
